// Copyright (c) 2025, Novigo Technology and contributors
// For license information, please see license.txt
// import { __ } from "../utils";

let translatableLocale = {
	accept: __("Yes"),
	addRule: __("Add Rule"),
	am: __("AM"),
	apply: __("Apply"),
	cancel: __("Cancel"),
	choose: __("Choose"),
	chooseDate: __("Choose Date"),
	chooseMonth: __("Choose Month"),
	chooseYear: __("Choose Year"),
	clear: __("Clear"),
	completed: __("Completed"),
	contains: __("Contains"),
	custom: __("Custom"),
	dateAfter: __("Date is after"),
	dateBefore: __("Date is before"),
	//TODO: Check if this is correct
	//dateFormat: __("mm/dd/yy"),
	dateIs: __("Date is"),
	dateIsNot: __("Date is not"),
	dayNames: [
		__("Sunday"),
		__("Monday"),
		__("Tuesday"),
		__("Wednesday"),
		__("Thursday"),
		__("Friday"),
		__("Saturday"),
	],
	dayNamesMin: [__("Su"), __("Mo"), __("Tu"), __("We"), __("Th"), __("Fr"), __("Sa")],
	dayNamesShort: [__("Sun"), __("Mon"), __("Tue"), __("Wed"), __("Thu"), __("Fri"), __("Sat")],
	emptyFilterMessage: __("No results found"),
	emptyMessage: __("No available options"),
	emptySearchMessage: __("No results found"),
	emptySelectionMessage: __("No selected item"),
	endsWith: __("Ends with"),
	equals: __("Equals"),
	fileChosenMessage: __("{0} files"),
	fileSizeTypes: [
		__("B"),
		__("KB"),
		__("MB"),
		__("GB"),
		__("TB"),
		__("PB"),
		__("EB"),
		__("ZB"),
		__("YB"),
	],
	filter: __("Filter"),
	firstDayOfWeek: 0,
	gt: __("Greater than"),
	gte: __("Greater than or equal to"),
	lt: __("Less than"),
	lte: __("Less than or equal to"),
	matchAll: __("Match All"),
	matchAny: __("Match Any"),
	medium: __("Medium"),
	monthNames: [
		__("January"),
		__("February"),
		__("March"),
		__("April"),
		__("May"),
		__("June"),
		__("July"),
		__("August"),
		__("September"),
		__("October"),
		__("November"),
		__("December"),
	],
	monthNamesShort: [
		__("Jan"),
		__("Feb"),
		__("Mar"),
		__("Apr"),
		__("May"),
		__("Jun"),
		__("Jul"),
		__("Aug"),
		__("Sep"),
		__("Oct"),
		__("Nov"),
		__("Dec"),
	],
	nextDecade: __("Next Decade"),
	nextHour: __("Next Hour"),
	nextMinute: __("Next Minute"),
	nextMonth: __("Next Month"),
	nextSecond: __("Next Second"),
	nextYear: __("Next Year"),
	noFileChosenMessage: __("No file chosen"),
	noFilter: __("No Filter"),
	notContains: __("Not contains"),
	notEquals: __("Not equals"),
	now: __("Now"),
	passwordPrompt: __("Enter a password"),
	pending: __("Pending"),
	pm: __("PM"),
	prevDecade: __("Previous Decade"),
	prevHour: __("Previous Hour"),
	prevMinute: __("Previous Minute"),
	prevMonth: __("Previous Month"),
	prevSecond: __("Previous Second"),
	prevYear: __("Previous Year"),
	reject: __("No"),
	removeRule: __("Remove Rule"),
	searchMessage: __("{0} results are available"),
	selectionMessage: __("{0} items selected"),
	//TODO: Check if this is correct
	//showMonthAfterYear: false,
	startsWith: __("Starts with"),
	strong: __("Strong"),
	today: __("Today"),
	upload: __("Upload"),
	weak: __("Weak"),
	weekHeader: __("Wk"),
	aria: {
		cancelEdit: __("Cancel Edit"),
		close: __("Close"),
		collapseLabel: __("Collapse"),
		collapseRow: __("Row Collapsed"),
		editRow: __("Edit Row"),
		expandLabel: __("Expand"),
		expandRow: __("Row Expanded"),
		falseLabel: __("False"),
		filterConstraint: __("Filter Constraint"),
		filterOperator: __("Filter Operator"),
		firstPageLabel: __("First Page"),
		gridView: __("Grid View"),
		hideFilterMenu: __("Hide Filter Menu"),
		jumpToPageDropdownLabel: __("Jump to Page Dropdown"),
		jumpToPageInputLabel: __("Jump to Page Input"),
		lastPageLabel: __("Last Page"),
		listLabel: __("Option List"),
		listView: __("List View"),
		moveAllToSource: __("Move All to Source"),
		moveAllToTarget: __("Move All to Target"),
		moveBottom: __("Move Bottom"),
		moveDown: __("Move Down"),
		moveToSource: __("Move to Source"),
		moveToTarget: __("Move to Target"),
		moveTop: __("Move Top"),
		moveUp: __("Move Up"),
		navigation: __("Navigation"),
		next: __("Next"),
		nextPageLabel: __("Next Page"),
		nullLabel: __("Not Selected"),
		otpLabel: __("Please enter one time password character {0}"),
		pageLabel: __("Page {page}"),
		passwordHide: __("Hide Password"),
		passwordShow: __("Show Password"),
		previous: __("Previous"),
		prevPageLabel: __("Previous Page"),
		removeLabel: __("Remove"),
		rotateLeft: __("Rotate Left"),
		rotateRight: __("Rotate Right"),
		rowsPerPageLabel: __("Rows per page"),
		saveEdit: __("Save Edit"),
		scrollTop: __("Scroll Top"),
		selectAll: __("All items selected"),
		selectLabel: __("Select"),
		selectRow: __("Row Selected"),
		showFilterMenu: __("Show Filter Menu"),
		slide: __("Slide"),
		//TODO: Check if this is correct
		//slideNumber: __("{slideNumber}"),
		star: __("1 star"),
		stars: __("{star} stars"),
		trueLabel: __("True"),
		unselectAll: __("All items unselected"),
		unselectLabel: __("Unselect"),
		unselectRow: __("Row Unselected"),
		zoomImage: __("Zoom Image"),
		zoomIn: __("Zoom In"),
		zoomOut: __("Zoom Out"),
	},
};

export default translatableLocale;
